### ISSUE TITLE
[Bug] Game crashed when place a turret

### ISSUE THREAD

**Issue by IceCola97** [Pitan76/CubicTurret#2]
There is the log:
[Versions and installed mods]
[17:25:29] [main/INFO]: Loading Minecraft 1.21.1 with Fabric Loader 0.16.9
[17:25:29] [main/INFO]: Loading 60 mods:
	- architectury 13.0.8
	- cubicturret 1.0.5
	- fabric-api 0.108.0+1.21.1
	   |-- fabric-api-base 0.4.42+6573ed8c19
	   |-- fabric-api-lookup-api-v1 1.6.70+b559734419
	   |-- fabric-biome-api-v1 13.0.30+be1ed2d719
	   |-- fabric-block-api-v1 1.0.22+0af3f5a719
	   |-- fabric-block-view-api-v2 1.0.10+6573ed8c19
	   |-- fabric-blockrenderlayer-v1 1.1.52+0af3f5a719
	   |-- fabric-client-tags-api-v1 1.1.15+6573ed8c19
	   |-- fabric-command-api-v1 1.2.49+f71b366f19
	   |-- fabric-command-api-v2 2.2.28+6ced4dd919
	   |-- fabric-commands-v0 0.2.66+df3654b319
	   |-- fabric-content-registries-v0 8.0.18+b559734419
	   |-- fabric-convention-tags-v1 2.1.2+7f945d5b19
	   |-- fabric-convention-tags-v2 2.9.2+e60e56d419
	   |-- fabric-crash-report-info-v1 0.2.29+0af3f5a719
	   |-- fabric-data-attachment-api-v1 1.3.0+8e331c5719
	   |-- fabric-data-generation-api-v1 20.2.23+16c4ae2519
	   |-- fabric-dimensions-v1 4.0.0+6fc22b9919
	   |-- fabric-entity-events-v1 1.7.0+2122d82819
	   |-- fabric-events-interaction-v0 0.7.13+ba9dae0619
	   |-- fabric-game-rule-api-v1 1.0.53+6ced4dd919
	   |-- fabric-item-api-v1 11.1.1+d5debaed19
	   |-- fabric-item-group-api-v1 4.1.6+6823f7cd19
	   |-- fabric-key-binding-api-v1 1.0.47+0af3f5a719
	   |-- fabric-keybindings-v0 0.2.45+df3654b319
	   |-- fabric-lifecycle-events-v1 2.5.0+01d9a51c19
	   |-- fabric-loot-api-v2 3.0.15+3f89f5a519
	   |-- fabric-loot-api-v3 1.0.3+3f89f5a519
	   |-- fabric-message-api-v1 6.0.13+6573ed8c19
	   |-- fabric-model-loading-api-v1 2.0.0+fe474d6b19
	   |-- fabric-networking-api-v1 4.3.0+c7469b2119
	   |-- fabric-object-builder-api-v1 15.2.1+40875a9319
	   |-- fabric-particles-v1 4.0.2+6573ed8c19
	   |-- fabric-recipe-api-v1 5.0.13+6508971219
	   |-- fabric-registry-sync-v0 5.1.3+60c3209b19
	   |-- fabric-renderer-api-v1 3.4.0+c705a49c19
	   |-- fabric-renderer-indigo 1.7.0+c705a49c19
	   |-- fabric-renderer-registries-v1 3.2.68+df3654b319
	   |-- fabric-rendering-data-attachment-v1 0.3.48+73761d2e19
	   |-- fabric-rendering-fluids-v1 3.1.6+1daea21519
	   |-- fabric-rendering-v0 1.1.71+df3654b319
	   |-- fabric-rendering-v1 5.0.5+df16efd019
	   |-- fabric-resource-conditions-api-v1 4.3.0+8dc279b119
	   |-- fabric-resource-loader-v0 1.3.1+5b5275af19
	   |-- fabric-screen-api-v1 2.0.25+8b68f1c719
	   |-- fabric-screen-handler-api-v1 1.3.87+b559734419
	   |-- fabric-sound-api-v1 1.0.23+6573ed8c19
	   |-- fabric-transfer-api-v1 5.4.2+95bead5f19
	   \-- fabric-transitive-access-wideners-v1 6.1.0+1daea21519
	- fabricloader 0.16.9
	   \-- mixinextras 0.4.1
	- java 21
	- mcpitanlib 3.1.2-1.21.1-fabric
	   |-- cloth-config 15.0.140
	   |    \-- cloth-basic-math 0.6.1
	   |-- compatdatapacks76 1.0.10.210-fabric
	   \-- org_yaml_snakeyaml 2.0
	- minecraft 1.21.1

[Exception stacktrace]
[17:26:08] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2248.method_9564()" because "block" is null
	at knot/net.pitan76.mcpitanlib.api.util.BlockStateUtil.getDefaultState(BlockStateUtil.java:47) ~[mcpitanlib-3.1.2-1.21.1-fabric.jar:?]
	at knot/net.pitan76.mcpitanlib.api.block.args.v2.PlacementStateArgs.getRawBlockState(PlacementStateArgs.java:140) ~[mcpitanlib-3.1.2-1.21.1-fabric.jar:?]
	at knot/net.pitan76.mcpitanlib.api.block.args.v2.PlacementStateArgs.getBlockState(PlacementStateArgs.java:160) ~[mcpitanlib-3.1.2-1.21.1-fabric.jar:?]
	at knot/net.pitan76.mcpitanlib.midohra.holder.BlockStatePropertyHolder.with(BlockStatePropertyHolder.java:12) ~[mcpitanlib-3.1.2-1.21.1-fabric.jar:?]
	at knot/net.pitan76.mcpitanlib.midohra.holder.BlockStatePropertyHolder.with(BlockStatePropertyHolder.java:29) ~[mcpitanlib-3.1.2-1.21.1-fabric.jar:?]
	at knot/net.pitan76.cubicturret.block.AbstractCubicTurretBlock.getPlacementState(AbstractCubicTurretBlock.java:61) ~[cubicturret-1.0.5.jar:?]
	at knot/net.pitan76.mcpitanlib.api.block.v2.CompatBlock.method_9605(CompatBlock.java:94) ~[mcpitanlib-3.1.2-1.21.1-fabric.jar:?]
	at knot/net.minecraft.class_1747.method_7707(class_1747.java:126) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1747.method_7712(class_1747.java:71) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1747.method_7884(class_1747.java:46) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1799.method_7981(class_1799.java:373) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_636.method_41934(class_636.java:363) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_636.method_41933(class_636.java:318) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_636.method_41931(class_636.java:279) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_636.method_2896(class_636.java:317) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1583(class_310.java:1852) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1508(class_310.java:2111) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1574(class_310.java:1938) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1246) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at mio.Wrapper.main(Wrapper.java:21) [MioLaunchWrapper.jar:?]

**Comment by IceCola97** [comment]
Additionally, the aforementioned issue also occurs in the mcpitanlib version 3.1.3
